/**
 * Auto-generated resolver factory.
 *
 * Takes a ParsedSchema and ApiDependencies, produces a resolver map
 * matching the GraphQL schema generated by ODL codegen.
 *
 * Query resolvers (Section 8.1.1):
 *   foo(id)      → authenticate → authorise → get → redact → consent
 *   foos(filter) → authenticate → listObjects → query → redact → consent
 *
 * Mutation resolvers (Section 8.1.2):
 *   Each ActionType → ActionExecutor.execute
 *
 * Subscription resolvers (Section 8.1.4):
 *   fooChanged(id) → PubSub filter
 */

import type { ParsedSchema, ObjectType, ActionType, FunctionType, FieldDefinition, LinkType, LinkDirective } from '@altius/odl';
import { DataPurpose } from '@altius/spi';
import type { OntologyObject, OntologyLink, FilterExpression, AggregateQuery, AggregateField, AggregateFunction, BucketInterval, SearchQuery, ErrorCategory, RequestContext } from '@altius/spi';
import { ToolRegistry } from '@altius/actions';
import type { ActionActor, ActionContext, ActionManifest } from '@altius/actions';
import type { RedactionResult } from '@altius/security';
import { PubSub } from 'graphql-subscriptions';
import type { ApiDependencies, ResolverContext, PaginationArgs } from './types.js';
import { DEFAULT_CONSENT_PURPOSE, DEFAULT_CONSENT_SUBJECT_TYPES, DEFAULT_PAGE_SIZE, isConsentSubjectType } from './types.js';
import { resolvePagination, buildConnection, decodeCursor } from './pagination.js';
import { paginateWithConsent } from '../consent-pagination.js';
import { createAltiusError, wrapError } from './errors.js';
import {
  createIdFilteredSubscription,
  createFilteredSubscription,
} from '../subscriptions/subscription-manager.js';
import { lowerFirst, toSnakeCase } from '../utils.js';
import { invokeFunction } from '../functions/invoke-function.js';
import {
  buildCdmMetadata,
  handleObjectRead,
  handleObjectList,
  handleEncounterSearch,
  OBJECT_SOURCE_TYPES,
} from '../cdm/index.js';
import { applyRelationshipChange } from '../relationships/router.js';
import { applyConsentRecord } from '../consent/router.js';

// ─── Helpers ───

function isPrimaryField(field: FieldDefinition): boolean {
  return field.directives.some(d => d.kind === 'primary');
}

function isParamField(field: FieldDefinition): boolean {
  return field.directives.some(d => d.kind === 'param');
}

/**
 * Recursively collect field names referenced in a GraphQL filter object.
 * Used to enforce field-level authorization on filter predicates.
 */
function collectGraphQLFilterFields(filter: Record<string, unknown> | undefined): string[] {
  if (!filter) return [];
  const fields: string[] = [];
  for (const [key, value] of Object.entries(filter)) {
    if (value == null) continue;
    if ((key === 'AND' || key === 'OR') && Array.isArray(value)) {
      for (const sub of value) {
        fields.push(...collectGraphQLFilterFields(sub as Record<string, unknown>));
      }
    } else if (key === 'NOT' && typeof value === 'object') {
      fields.push(...collectGraphQLFilterFields(value as Record<string, unknown>));
    } else {
      fields.push(key);
    }
  }
  return fields;
}

/**
 * Convert GraphQL filter input to SPI FilterExpression.
 * The GraphQL filter uses scalar filter inputs like { eq, ne, in, ... }.
 * We translate these to SPI FieldPredicate form.
 */
function convertFilter(filter: Record<string, unknown> | undefined): FilterExpression | undefined {
  if (!filter) return undefined;

  const predicates: FilterExpression[] = [];

  for (const [key, value] of Object.entries(filter)) {
    if (value == null) continue;

    if (key === 'AND' && Array.isArray(value)) {
      const subFilters = value.map((v: Record<string, unknown>) => convertFilter(v)).filter(Boolean) as FilterExpression[];
      if (subFilters.length > 0) {
        predicates.push({ and: subFilters });
      }
      continue;
    }
    if (key === 'OR' && Array.isArray(value)) {
      const subFilters = value.map((v: Record<string, unknown>) => convertFilter(v)).filter(Boolean) as FilterExpression[];
      if (subFilters.length > 0) {
        predicates.push({ or: subFilters });
      }
      continue;
    }
    if (key === 'NOT' && typeof value === 'object') {
      const sub = convertFilter(value as Record<string, unknown>);
      if (sub) predicates.push({ not: sub });
      continue;
    }

    // Scalar filter: { field: { eq: "x", gt: 5, ... } }
    if (typeof value === 'object' && !Array.isArray(value)) {
      const ops = value as Record<string, unknown>;
      for (const [op, opVal] of Object.entries(ops)) {
        if (opVal == null) continue;
        const spiOp = mapFilterOp(op);
        if (spiOp) {
          predicates.push({ field: key, operator: spiOp, value: opVal });
        }
      }
    }
  }

  if (predicates.length === 0) return undefined;
  if (predicates.length === 1) return predicates[0];
  return { and: predicates };
}

type SpiOperator = 'eq' | 'neq' | 'gt' | 'gte' | 'lt' | 'lte' | 'in' | 'contains' | 'startsWith' | 'exists';

function mapFilterOp(op: string): SpiOperator | undefined {
  const mapping: Record<string, SpiOperator> = {
    eq: 'eq',
    ne: 'neq',
    gt: 'gt',
    gte: 'gte',
    lt: 'lt',
    lte: 'lte',
    in: 'in',
    contains: 'contains',
    startsWith: 'startsWith',
    exists: 'exists',
  };
  return mapping[op];
}

/**
 * Convert GraphQL orderBy input to SPI QueryOptions.orderBy.
 */
function convertOrderBy(orderBy: Record<string, string> | undefined): { field: string; direction: 'asc' | 'desc' }[] | undefined {
  if (!orderBy) return undefined;
  const result: { field: string; direction: 'asc' | 'desc' }[] = [];
  for (const [field, dir] of Object.entries(orderBy)) {
    if (dir) {
      result.push({ field, direction: dir.toLowerCase() as 'asc' | 'desc' });
    }
  }
  return result.length > 0 ? result : undefined;
}

/**
 * Extract all field names referenced in a filter expression.
 * Used to validate that users cannot filter/sort on redacted fields.
 */
export function extractFilterFields(filter: FilterExpression | undefined): Set<string> {
  const fields = new Set<string>();
  if (!filter) return fields;

  function walk(expr: FilterExpression): void {
    if ('field' in expr) {
      fields.add((expr as { field: string }).field);
      return;
    }
    const logical = expr as { and?: FilterExpression[]; or?: FilterExpression[]; not?: FilterExpression };
    if (logical.and) {
      for (const sub of logical.and) walk(sub);
    }
    if (logical.or) {
      for (const sub of logical.or) walk(sub);
    }
    if (logical.not) {
      walk(logical.not);
    }
  }
  walk(filter);
  return fields;
}

/**
 * Validate that filter and sort fields are not targeting redacted fields.
 * Returns the set of disallowed field names, or empty set if all are valid.
 */
export function validateQueryFields(
  filterFields: Set<string>,
  orderByFields: string[],
  visibleFields: Set<string> | undefined,
): string[] {
  // No field config → all fields visible (no redaction configured)
  if (!visibleFields) return [];

  const violations: string[] = [];
  for (const field of filterFields) {
    // System fields (_id) are always allowed for filtering
    if (field.startsWith('_')) continue;
    if (!visibleFields.has(field)) violations.push(field);
  }
  for (const field of orderByFields) {
    if (field.startsWith('_')) continue;
    if (!visibleFields.has(field)) violations.push(field);
  }
  return violations;
}

/**
 * Convert an OntologyObject to a GraphQL-friendly shape.
 * Strips the underscore prefix from system fields that map to schema fields.
 */
export function objectToGraphQL(obj: OntologyObject, objectType: ObjectType): Record<string, unknown> {
  const result: Record<string, unknown> = {};

  for (const field of objectType.fields) {
    if (isPrimaryField(field)) {
      // Primary field is an alias for the system _id column — the field name
      // can be anything (id, mrn, sku); the value always comes from obj._id.
      result[field.name] = obj._id;
    } else {
      result[field.name] = obj[field.name];
    }
  }

  // Stamp the concrete type name so interface `__resolveType` resolvers can
  // return the implementing ObjectType without a separate lookup. graphql-tools
  // exposes `__typename` as a default field, so this is also queryable.
  result.__typename = objectType.name;

  // Include system metadata. `_id` is not in the generated SDL (so it never
  // reaches a client), but downstream steps identify the row by it — the list
  // and search paths resolve the consent subject from `_id`, and without it
  // every row is checked as subject '' and default-denied.
  result._id = obj._id;
  // `_version` is what callers pass back as `expectedVersion` on update/delete
  // mutations and `_expectedVersion` on action inputs; it is in the SDL.
  result._version = obj._version;
  result._redactedFields = null;
  result._consentRestricted = false;

  return result;
}

/**
 * Map an OntologyLink record to its GraphQL shape (for link fields whose type
 * IS the link type, e.g. Patient.admissions: [AdmittedTo!]!). Link properties
 * are stored as top-level keys on the link record; the primary field maps to _id.
 */
function linkToGraphQL(link: OntologyLink, linkType: LinkType): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const field of linkType.fields) {
    if (isPrimaryField(field)) {
      // Primary field is an alias for the system _id column.
      result[field.name] = link._id;
    } else {
      result[field.name] = link[field.name];
    }
  }
  return result;
}

/** The @link directive on a field, if present. */
function linkDirectiveOf(field: FieldDefinition): LinkDirective | undefined {
  return field.directives.find((d): d is LinkDirective => d.kind === 'link');
}

/**
 * Generate type-level field resolvers for an object type's @link fields, so
 * GraphQL nested relationship traversal works (e.g. patient.currentWard,
 * ward.beds, patient.admissions). Without these the generated schema exposes
 * link fields but graphql-tools returns the raw (absent) property → null.
 *
 * For a field whose type is an ObjectType (currentWard: Ward) we resolve the
 * linked TARGET objects; for a field whose type IS the link type
 * (admissions: [AdmittedTo!]!) we return the link records themselves. Both honour
 * field-level redaction; target objects also honour consent (parity with the
 * single-object query resolver). The parent object was already authorised when
 * it was resolved, matching the REST /links endpoint (which checks the parent).
 */
function generateLinkFieldResolvers(
  obj: ObjectType,
  schema: ParsedSchema,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const linked = obj.fields
    .map((field) => ({ field, link: linkDirectiveOf(field) }))
    .filter((x): x is { field: FieldDefinition; link: LinkDirective } => x.link !== undefined);
  if (linked.length === 0) return;

  const primaryName = obj.fields.find(isPrimaryField)?.name ?? 'id';
  const typeResolvers: Record<string, ResolverValue> = resolvers[obj.name] ?? {};

  for (const { field, link } of linked) {
    const direction: 'inbound' | 'outbound' = link.direction === 'INBOUND' ? 'inbound' : 'outbound';
    const isList = field.type.isList;
    const targetTypeName = field.type.name;
    const linkTypeDef = schema.linkTypes.find((lt) => lt.name === link.type);
    const targetObjectType = schema.objectTypes.find((ot) => ot.name === targetTypeName);
    const targetFgaType = toSnakeCase(targetTypeName);
    // Field type IS the link type → return link records (history); otherwise
    // the field type is the linked object type → return target objects.
    const returnsLinkRecords = targetTypeName === link.type;
    // @link(history: true) fields (e.g. Patient.admissions) include soft-deleted
    // links so completed/discharged records remain visible — parity with the
    // FHIR/CDM Encounter projections.
    const includeDeleted = link.history === true;

    typeResolvers[field.name] = async (
      parent: Record<string, unknown>,
      _args: unknown,
      ctx: ResolverContext,
    ) => {
      try {
        const parentId = parent[primaryName] as string | undefined;
        if (!parentId) return isList ? [] : null;
        const { user, requestContext } = ctx;

        const page = await deps.linkManager.getLinks(
          parentId,
          link.type,
          direction,
          { limit: isList ? 1000 : 1, offset: 0, includeDeleted },
          requestContext,
        );
        const links = page.items;

        // Link-record fields (e.g. admissions): return the links themselves.
        if (returnsLinkRecords) {
          if (!linkTypeDef) return isList ? [] : null;
          const mapped = deps.authorizationService
            .redactFieldsBatch(
              user.id,
              user.roles,
              link.type,
              links.map((l) => linkToGraphQL(l, linkTypeDef)),
            )
            .map((r: RedactionResult<Record<string, unknown>>) => r.data as Record<string, unknown>);
          return isList ? mapped : (mapped[0] ?? null);
        }

        // Target-object fields (e.g. currentWard): resolve the linked objects.
        if (!targetObjectType) return isList ? [] : null;
        const targets: Record<string, unknown>[] = [];
        const seen = new Set<string>();
        for (const l of links) {
          const targetId = direction === 'outbound' ? l._toId : l._fromId;
          if (seen.has(targetId)) continue;
          seen.add(targetId);

          // Per-target authorization — parity with the root foo(id) resolver.
          // Without this, traversal (e.g. ward.patients) could surface objects
          // the caller could not fetch directly. Targets the user cannot view
          // are silently dropped (list) / yield null (single).
          const allowed = await deps.authorizationService.check(
            `user:${user.id}`,
            'viewer',
            `${targetFgaType}:${targetId}`,
            user.tenantId,
          );
          if (!allowed) continue;

          const target = await deps.objectManager.get(targetTypeName, targetId, requestContext);
          if (!target) continue;

          let gqlObj = objectToGraphQL(target, targetObjectType);
          const redacted = deps.authorizationService.redactFields(
            user.id,
            user.roles,
            targetTypeName,
            gqlObj,
          );
          gqlObj = redacted.data as Record<string, unknown>;
          gqlObj._redactedFields = redacted._redactedFields.length > 0 ? redacted._redactedFields : null;

          if (deps.consentService && isConsentSubjectType(targetTypeName, deps.consentSubjectTypes)) {
            const consentResult = await deps.consentService.checkSingleObject(
              gqlObj,
              targetId,
              DEFAULT_CONSENT_PURPOSE as DataPurpose,
              user.id,
              requestContext.tenantId,
            );
            if (consentResult._consentRestricted) {
              gqlObj._consentRestricted = true;
              for (const f of targetObjectType.fields) {
                if (!isPrimaryField(f)) gqlObj[f.name] = null;
              }
            }
          }

          targets.push(gqlObj);
          if (!isList) break;
        }
        return isList ? targets : (targets[0] ?? null);
      } catch (err) {
        throw wrapError(err, ctx.requestContext.traceId);
      }
    };
  }

  resolvers[obj.name] = typeResolvers;
}

/**
 * Generate the `history` field resolver for an object type.
 *
 * Returns all stored versions of the parent object, oldest first, using the
 * batch `getObjectHistory` SPI method (one query) instead of the N+1 loop the
 * REST route used to make. Each version is shaped, redacted, and consent-
 * filtered exactly like the single-object get path — the history timeline
 * shows the caller the same fields they could see at the time.
 */
function generateHistoryFieldResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeResolvers: Record<string, ResolverValue> = resolvers[obj.name] ?? {};
  const primaryName = obj.fields.find(isPrimaryField)?.name ?? 'id';
  const fgaType = toSnakeCase(obj.name);

  typeResolvers['history'] = async (
    parent: Record<string, unknown>,
    _args: unknown,
    ctx: ResolverContext,
  ) => {
    try {
      const id = parent[primaryName] as string | undefined;
      if (!id) return [];
      const { user, requestContext } = ctx;

      // Authorize — the caller must have view access to the object itself.
      // Without this, history would bypass the FGA check that gates every
      // other read of this object.
      const allowed = await deps.authorizationService.check(
        `user:${user.id}`,
        'viewer',
        `${fgaType}:${id}`,
        user.tenantId,
      );
      if (!allowed) return [];

      const versions = await deps.storage.getObjectHistory(
        requestContext,
        obj.name,
        id,
      );

      const redacted = deps.authorizationService.redactFieldsBatch(
        user.id,
        user.roles,
        obj.name,
        versions.map((v) => objectToGraphQL(v, obj)),
      );

      let items = redacted.map((r: RedactionResult<Record<string, unknown>>) => {
        const data = r.data as Record<string, unknown>;
        data._redactedFields = r._redactedFields.length > 0 ? r._redactedFields : null;
        data._consentRestricted = false;
        return data;
      });

      // Consent filtering — parity with the REST history route.
      if (deps.consentService && isConsentSubjectType(obj.name, deps.consentSubjectTypes)) {
        const getPrimaryId = (item: Record<string, unknown>) => String(item._id ?? '');
        const consentResult = await deps.consentService.filterList(
          items,
          getPrimaryId,
          DEFAULT_CONSENT_PURPOSE as DataPurpose,
          user.id,
          requestContext.tenantId,
        );
        items = consentResult.edges;
      }

      return items;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  resolvers[obj.name] = typeResolvers;
}

// ─── Resolver map type ───

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ResolverFn = (...args: any[]) => any;
type SubscriptionResolver = { subscribe: ResolverFn };
type ResolverValue = ResolverFn | SubscriptionResolver;
type ResolverMap = Record<string, Record<string, ResolverValue>>;

// ─── Public API ───

/**
 * Generate resolver map from ParsedSchema and dependencies.
 * Returns { resolvers, pubsub } where resolvers is the complete resolver map
 * and pubsub can be used to publish subscription events.
 */
export function generateResolvers(
  schema: ParsedSchema,
  deps: ApiDependencies,
): { resolvers: ResolverMap; pubsub: PubSub } {
  const pubsub = new PubSub();
  const resolvers: ResolverMap = {
    Query: {},
    Mutation: {},
    Subscription: {},
  };

  // Generate query resolvers for each ObjectType
  for (const obj of schema.objectTypes) {
    generateQueryResolvers(obj, resolvers, deps);
    generateAggregateResolver(obj, resolvers, deps);
    generateSearchResolver(obj, resolvers, deps);
    generateSubscriptionResolvers(obj, resolvers, pubsub);
    // Type-level resolvers for @link fields (nested relationship traversal).
    generateLinkFieldResolvers(obj, schema, resolvers, deps);
    // `history` field resolver — batch version fetch with redaction + consent.
    generateHistoryFieldResolver(obj, resolvers, deps);
    // Generic update/delete mutations with optional expectedVersion input
    // for client-facing optimistic concurrency (#5).
    generateUpdateMutationResolver(obj, resolvers, deps);
    generateDeleteMutationResolver(obj, resolvers, deps);
  }

  // Interface `__resolveType` resolvers. Object types resolve by name — the
  // concrete type is stamped on the GraphQL object by `objectToGraphQL` as
  // `__typename`, so resolution is a property read. This lets interface-typed
  // fields (e.g. a union-like field returning any Auditable) resolve to the
  // implementing ObjectType without a per-field custom resolver.
  for (const iface of schema.interfaces) {
    resolvers[iface.name] = {
      __resolveType: (parent: Record<string, unknown>) => parent.__typename as string | undefined,
    };
  }

  // Interface-typed list resolvers — what makes the __resolveType above
  // reachable. Until now nothing in the schema returned an interface, so those
  // resolvers were unreachable code and a caller could not ask for "every
  // Locatable" without naming each concrete type itself.
  //
  // Each one delegates to the implementors' existing plural resolvers rather
  // than querying storage directly. That is deliberate: authorization, field
  // redaction and consent all live in that path, and a second read path is a
  // second place for them to drift apart.
  for (const iface of schema.interfaces) {
    const implementors = schema.objectTypes.filter(o => o.interfaces.includes(iface.name));
    if (implementors.length === 0) continue;

    const fieldName = `${lowerFirst(iface.name)}s`;
    // Codegen skips the SDL field when an ObjectType plural already owns the
    // name; skip the resolver on the same condition so the two stay in step.
    if (resolvers['Query']![fieldName]) continue;

    resolvers['Query']![fieldName] = async (
      parent: unknown,
      args: { first?: number },
      ctx: ResolverContext,
    ) => {
      const limit = args.first ?? DEFAULT_PAGE_SIZE;
      const results: Record<string, unknown>[] = [];

      for (const impl of implementors) {
        const delegate = resolvers['Query']![`${lowerFirst(impl.name)}s`];
        if (typeof delegate !== 'function') continue;
        const connection = await delegate(parent, { first: limit }, ctx) as {
          edges?: { node: Record<string, unknown> }[];
        };
        for (const edge of connection.edges ?? []) results.push(edge.node);
      }

      // `first` bounds the whole result, not each implementor — asking for 10
      // Locatables must not return 10 per type.
      return results.slice(0, limit);
    };
  }

  // Generate mutation resolvers for each ActionType.
  // NOTE: Domain pack YAML action manifests are loaded at runtime via
  // ManifestRegistry but are NOT reflected in schema.actionTypes unless
  // the ODL schema includes @actionType directives. Until the schema
  // registry integrates pack manifest discovery, pack actions won't
  // appear as GraphQL/REST mutations automatically.
  for (const action of schema.actionTypes) {
    generateMutationResolver(action, schema, resolvers, deps);
  }

  // Generate mutation resolvers for each FunctionType (Section 6 — Functions).
  // Skipped when no functionExecutor is configured — the SDL still declares
  // the fields, but resolution will throw a configuration error if invoked.
  for (const fn of schema.functionTypes) {
    generateFunctionResolver(fn, resolvers, deps);
  }

  // availableTools query (Section 5.7)
  resolvers['Query']!['availableTools'] = generateAvailableToolsResolver(schema, deps);

  // Per-object action applicability: which actions target this object?
  resolvers['Query']!['applicableActions'] = generateApplicableActionsResolver(schema, deps);

  // Object Set resolvers
  generateObjectSetResolvers(resolvers, deps);

  // FDP/CDM read-only projection resolvers (cdmMetadata/cdmRecord/cdmRecords).
  // Capability-gated: omitted when the deployment's packs do not declare `cdm`
  // (mirrors the SDL gate + REST mount), so non-NHS deployments register none.
  if (deps.cdmEnabled !== false) {
    generateCdmResolvers(resolvers, deps);
  }

  // Relationship (care-team) grant/revoke resolvers (v0.2.0 A1).
  generateRelationshipResolvers(resolvers, deps);

  // Consent record resolver (v0.2.0 A2).
  generateConsentResolvers(resolvers, deps);

  return { resolvers, pubsub };
}

// ─── Query resolvers ───

function generateQueryResolvers(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const lower = lowerFirst(typeName);
  const fgaType = toSnakeCase(typeName);

  // Single object query: foo(id: ID!): Foo
  resolvers['Query']![lower] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      // a. Authenticate (already done in context middleware)
      const { user, requestContext } = ctx;

      // b. Authorize: check user has viewer relation to this object
      const allowed = await deps.authorizationService.check(
        `user:${user.id}`,
        'viewer',
        `${fgaType}:${args.id}`,
        user.tenantId,
      );
      if (!allowed) {
        throw createAltiusError({
          code: 'FORBIDDEN',
          category: 'authorization',
          message: `Access denied to ${typeName} ${args.id}`,
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      // c. Get from engine
      const result = await deps.objectManager.get(typeName, args.id, requestContext);
      if (!result) {
        return null;
      }

      let gqlObj = objectToGraphQL(result, obj);

      // d. Field-level redaction
      const redacted = deps.authorizationService.redactFields(
        user.id,
        user.roles,
        typeName,
        gqlObj,
      );
      gqlObj = redacted.data as Record<string, unknown>;
      gqlObj._redactedFields = redacted._redactedFields.length > 0 ? redacted._redactedFields : null;

      // e. Consent filtering (single object)
      if (deps.consentService && isConsentSubjectType(typeName, deps.consentSubjectTypes)) {
        const consentResult = await deps.consentService.checkSingleObject(
          gqlObj,
          args.id,
          DEFAULT_CONSENT_PURPOSE as DataPurpose,
          user.id,
          requestContext.tenantId,
        );
        if (consentResult._consentRestricted) {
          gqlObj._consentRestricted = true;
          // Redact all non-primary fields for consent-restricted objects
          for (const field of obj.fields) {
            if (!isPrimaryField(field)) {
              gqlObj[field.name] = null;
            }
          }
        }
      }

      return gqlObj;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // List query: foos(filter, orderBy, first, after, last, before): FooConnection!
  resolvers['Query']![`${lower}s`] = async (
    _parent: unknown,
    args: { filter?: Record<string, unknown>; orderBy?: Record<string, string> } & PaginationArgs,
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // a. Authenticate (already done in context)

      // b. Authorization: list objects user can see
      const allowedObjects = await deps.authorizationService.listObjects(
        `user:${user.id}`,
        'viewer',
        fgaType,
        user.tenantId,
      );

      // Build filter: combine user filter with authorization filter
      const userFilter = convertFilter(args.filter);

      // SEC-14: Validate filter/sort fields against redacted fields
      // Prevents users from inferring hidden field values via predicate leakage.
      const visibleFields = deps.authorizationService.getVisibleFields(user.id, user.roles, typeName);
      const orderByFields = args.orderBy ? Object.keys(args.orderBy) : [];
      const violations = validateQueryFields(
        extractFilterFields(userFilter),
        orderByFields,
        visibleFields,
      );
      if (violations.length > 0) {
        throw new Error(
          `Access denied: cannot filter or sort on redacted fields: ${violations.join(', ')}`,
        );
      }

      // Extract IDs from authorization results (format: "type:id").
      // Dev stub returns ['*'] sentinel meaning "all objects authorized".
      const allAuthorized = allowedObjects.length === 1 && allowedObjects[0] === '*';
      const allowedIds = allAuthorized ? [] : allowedObjects.map((o: string) => {
        const parts = o.split(':');
        return parts[parts.length - 1];
      }).filter((id): id is string => id !== undefined && id !== '');

      // SEC-11: If no objects are authorized, return empty connection immediately
      if (!allAuthorized && allowedIds.length === 0) {
        return buildConnection([], 0, 0);
      }

      // Build combined filter — skip ID restriction when all authorized.
      // Use _deleted_at IS NULL as a trivially-true base when no ID filter is needed.
      let combinedFilter: FilterExpression;
      if (!allAuthorized) {
        const idFilter: FilterExpression = {
          field: '_id',
          operator: 'in',
          value: allowedIds,
        };
        combinedFilter = userFilter ? { and: [idFilter, userFilter] } : idFilter;
      } else {
        const passThrough: FilterExpression = { field: '_deleted_at', operator: 'exists', value: false };
        combinedFilter = userFilter ? { and: [passThrough, userFilter] } : passThrough;
      }

      // c. Resolve pagination
      const { offset, limit } = resolvePagination(args);

      const mapAndRedact = (objs: OntologyObject[]): Record<string, unknown>[] =>
        deps.authorizationService
          .redactFieldsBatch(
            user.id,
            user.roles,
            typeName,
            objs.map((item: OntologyObject) => objectToGraphQL(item, obj)),
          )
          .map((r: RedactionResult<Record<string, unknown>>) => {
            const data = r.data as Record<string, unknown>;
            data._redactedFields = r._redactedFields.length > 0 ? r._redactedFields : null;
            data._consentRestricted = false;
            return data;
          });

      let items: Record<string, unknown>[];
      let totalCount: number;

      if (deps.consentService && isConsentSubjectType(typeName, deps.consentSubjectTypes)) {
        // Consent removes records, so filter BEFORE slicing the page (see
        // consent-pagination.ts) — DB-pagination then consent drops drifts
        // totalCount/hasNextPage and can hide later pages.
        const getPrimaryId = (item: Record<string, unknown>) => String(item._id ?? '');
        const result = await paginateWithConsent<OntologyObject, Record<string, unknown>>(
          offset,
          limit,
          async (windowLimit) => {
            const scan = await deps.objectManager.query(
              typeName, combinedFilter, { limit: windowLimit, offset: 0, orderBy: convertOrderBy(args.orderBy) }, requestContext,
            );
            return { items: scan.items, total: scan.totalCount };
          },
          async (raw) => {
            const consentResult = await deps.consentService!.filterList(
              mapAndRedact(raw), getPrimaryId, DEFAULT_CONSENT_PURPOSE as DataPurpose,
              user.id, requestContext.tenantId,
            );
            return consentResult.edges as Record<string, unknown>[];
          },
        );
        items = result.items;
        // Nudge totalCount so buildConnection's hasNextPage matches the helper
        // even when the scan window did not cover every matching row.
        totalCount = result.hasNextPage
          ? Math.max(result.totalCount, offset + items.length + 1)
          : result.totalCount;
      } else {
        const page = await deps.objectManager.query(
          typeName, combinedFilter, { limit, offset, orderBy: convertOrderBy(args.orderBy) }, requestContext,
        );
        items = mapAndRedact(page.items);
        totalCount = page.totalCount;
      }

      // g. Build Relay connection
      return buildConnection(items, totalCount, offset);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Auth helper ───

/**
 * Resolve authorized object IDs for a user+type via FGA listObjects.
 * Returns ['*'] when the dev stub signals all objects are authorized.
 */
/**
 * For consent-subject types, query all matching records, apply consent
 * filtering, and return the consented ID list. Returns ['*'] when consent is
 * not applicable (non-subject type or no consent service wired).
 *
 * This is used by aggregate to constrain the input set to consented records
 * before delegating to the storage aggregate — the list path does the same
 * via paginateWithConsent, but aggregate returns groups not records, so we
 * need the ID list up front.
 */
/**
 * How many records the per-record consent evaluation will scan before it gives
 * up. Mirrors CONSENT_SCAN_LIMIT in rest/route-generator.ts — both aggregate
 * paths must refuse at the same point or they disagree about the same query.
 */
const CONSENT_SCAN_LIMIT = 10_000;

async function resolveConsentedIds(
  deps: ApiDependencies,
  typeName: string,
  allowedIds: string[],
  userFilter: FilterExpression | undefined,
  userId: string,
  requestContext: RequestContext,
): Promise<string[]> {
  if (!deps.consentService || !isConsentSubjectType(typeName, deps.consentSubjectTypes)) {
    return allowedIds;
  }

  // Query all matching records (auth-filtered, no consent yet). One past the
  // window, so a full page is distinguishable from a truncated one.
  const combinedFilter = buildAuthFilter(allowedIds, userFilter);
  const scan = await deps.objectManager.query(
    typeName, combinedFilter, { limit: CONSENT_SCAN_LIMIT + 1, offset: 0 }, requestContext,
  );

  if (scan.items.length > CONSENT_SCAN_LIMIT) {
    // See the REST twin in rest/route-generator.ts: past this window the
    // aggregate would be computed over a truncated population and returned as
    // if complete. Refuse rather than answer with a wrong number.
    throw createAltiusError({
      code: 'QUOTA_EXCEEDED',
      category: 'quota',
      retryable: false,
      message:
        `Cannot aggregate ${typeName}: more than ${CONSENT_SCAN_LIMIT} records match and consent must be ` +
        `evaluated per record, so the result would be computed over a truncated population. Narrow the filter.`,
    });
  }

  // Apply consent filter to remove non-consented records
  const getPrimaryId = (item: OntologyObject) => String(item._id ?? '');
  const consentResult = await deps.consentService.filterList(
    scan.items, getPrimaryId, DEFAULT_CONSENT_PURPOSE as DataPurpose,
    userId, requestContext.tenantId,
  );

  return consentResult.edges.map(o => o._id);
}

export async function resolveAllowedIds(
  deps: ApiDependencies,
  userId: string,
  fgaType: string,
  tenantId: string,
): Promise<string[]> {
  const allowedObjects = await deps.authorizationService.listObjects(
    `user:${userId}`,
    'viewer',
    fgaType,
    tenantId,
  );
  if (allowedObjects.length === 1 && allowedObjects[0] === '*') {
    return ['*'];
  }
  return allowedObjects.map((o: string) => {
    const parts = o.split(':');
    return parts[parts.length - 1];
  }).filter((id): id is string => id !== undefined && id !== '');
}

/**
 * Build a combined filter that restricts to authorized IDs + optional user filter.
 * When allowedIds is ['*'] (dev stub), skip the ID restriction.
 */
export function buildAuthFilter(
  allowedIds: string[],
  userFilter?: FilterExpression,
): FilterExpression {
  const allAuthorized = allowedIds.length === 1 && allowedIds[0] === '*';
  if (allAuthorized) {
    const passThrough: FilterExpression = { field: '_deleted_at', operator: 'exists', value: false };
    return userFilter ? { and: [passThrough, userFilter] } : passThrough;
  }
  const idFilter: FilterExpression = {
    field: '_id',
    operator: 'in',
    value: allowedIds,
  };
  return userFilter ? { and: [idFilter, userFilter] } : idFilter;
}

// ─── Generic update/delete mutation resolvers (#5 — client-facing optimistic concurrency) ───

/**
 * Generate `updateFoo(id: ID!, input: UpdateFooInput!, expectedVersion: Int): Foo!`
 * for each ObjectType. The optional `expectedVersion` is forwarded to
 * `ObjectManager.update`, enabling client-facing optimistic concurrency.
 * A stale version raises `VERSION_CONFLICT` from the storage layer, which
 * `wrapError` maps to a GraphQL error with `code: VERSION_CONFLICT`.
 */
function generateUpdateMutationResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const fgaType = toSnakeCase(typeName);

  resolvers['Mutation']![`update${typeName}`] = async (
    _parent: unknown,
    args: { id: string; input: Record<string, unknown>; expectedVersion?: number },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;
      const id = args.id;

      // Authorize
      const allowed = await deps.authorizationService.check(
        `user:${user.id}`,
        'editor',
        `${fgaType}:${id}`,
        user.tenantId,
      );
      if (!allowed) {
        throw createAltiusError({
          code: 'FORBIDDEN',
          category: 'authorization',
          message: `Access denied to update ${typeName} ${id}`,
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      const updated = await deps.objectManager.update(
        typeName,
        id,
        args.input,
        requestContext,
        undefined,
        args.expectedVersion,
      );

      let shaped = objectToGraphQL(updated, obj);

      // Field-level redaction
      const redacted = deps.authorizationService.redactFields(
        user.id,
        user.roles,
        typeName,
        shaped,
      );
      shaped = redacted.data as Record<string, unknown>;
      shaped['_redactedFields'] = redacted._redactedFields.length > 0 ? redacted._redactedFields : null;

      return shaped;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

/**
 * Generate `deleteFoo(id: ID!, expectedVersion: Int): Boolean!`
 * for each ObjectType. Since the SPI `deleteObject` does not accept
 * `expectedVersion`, this resolver does a fetch-then-compare when
 * `expectedVersion` is provided.
 */
function generateDeleteMutationResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const fgaType = toSnakeCase(typeName);

  resolvers['Mutation']![`delete${typeName}`] = async (
    _parent: unknown,
    args: { id: string; expectedVersion?: number },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;
      const id = args.id;

      // Authorize
      const allowed = await deps.authorizationService.check(
        `user:${user.id}`,
        'editor',
        `${fgaType}:${id}`,
        user.tenantId,
      );
      if (!allowed) {
        throw createAltiusError({
          code: 'FORBIDDEN',
          category: 'authorization',
          message: `Access denied to delete ${typeName} ${id}`,
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      // Fetch-then-check for expectedVersion (SPI deleteObject has no expectedVersion)
      if (args.expectedVersion !== undefined && args.expectedVersion !== null) {
        const existing = await deps.objectManager.get(typeName, id, requestContext);
        if (!existing) {
          throw createAltiusError({
            code: 'OBJECT_NOT_FOUND',
            category: 'not_found',
            message: `${typeName} ${id} not found`,
            retryable: false,
            traceId: requestContext.traceId,
          });
        }
        if (existing._version !== args.expectedVersion) {
          throw createAltiusError({
            code: 'VERSION_CONFLICT',
            category: 'precondition',
            message: `Version mismatch: expected ${args.expectedVersion}, found ${existing._version}`,
            retryable: false,
            traceId: requestContext.traceId,
          });
        }
      }

      await deps.objectManager.delete(typeName, id, 'soft', requestContext);
      return true;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Aggregate resolvers ───

function generateAggregateResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const lower = lowerFirst(typeName);
  const fgaType = toSnakeCase(typeName);

  // fooAggregate(filter, groupBy, fields): AggregateResult!
  resolvers['Query']![`${lower}Aggregate`] = async (
    _parent: unknown,
    args: {
      filter?: Record<string, unknown>;
      groupBy?: string[];
      buckets?: Array<{ field: string; interval: string; alias?: string }>;
      fields: Array<{ field: string; fn: string; alias?: string }>;
    },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Authorization: restrict aggregation to authorized objects
      const allowedIds = await resolveAllowedIds(deps, user.id, fgaType, user.tenantId);
      if (allowedIds.length === 0) {
        return { groups: [], totalGroups: 0 };
      }

      // Field-level authorization: reject aggregation over redacted fields
      // Check aggregate fields, groupBy, and filter predicates
      const visibleFields = deps.authorizationService.getVisibleFields(user.id, user.roles, typeName);
      if (visibleFields) {
        const allRequestedFields = [
          ...args.fields.filter(f => f.field !== '*').map(f => f.field),
          ...(args.groupBy ?? []),
          ...(args.buckets ?? []).map(b => b.field),
          ...collectGraphQLFilterFields(args.filter),
        ];
        const blocked = allRequestedFields.filter(f => !visibleFields.has(f));
        if (blocked.length > 0) {
          throw createAltiusError({
            code: 'FORBIDDEN',
            category: 'authorization',
            message: `Cannot aggregate over redacted fields: ${blocked.join(', ')}`,
            retryable: false,
            traceId: requestContext.traceId,
          });
        }
      }

      // Convert GraphQL filter to SPI filter and combine with auth filter
      const userFilter = convertFilter(args.filter);

      // Consent gate: for consent-subject types, constrain the aggregate to
      // consented records only. Without this, a user could aggregate over
      // records they have no consent for (e.g. population stats over patients
      // who opted out). The list path applies consent via paginateWithConsent;
      // aggregate returns groups, so we resolve the consented ID set up front
      // and pass it as a filter to the storage aggregate.
      const consentedIds = await resolveConsentedIds(
        deps, typeName, allowedIds, userFilter, user.id, requestContext,
      );
      if (consentedIds.length === 0 || (consentedIds.length === 1 && consentedIds[0] === '*' && allowedIds.length === 0)) {
        return { groups: [], totalGroups: 0 };
      }
      const combinedFilter = buildAuthFilter(consentedIds, userFilter);

      // Convert GraphQL aggregate fields to SPI AggregateField[]
      const fields: AggregateField[] = args.fields.map((f) => ({
        field: f.field,
        fn: f.fn.toLowerCase() as AggregateFunction,
        alias: f.alias,
      }));

      const query: AggregateQuery = {
        fields,
        groupBy: args.groupBy,
        buckets: args.buckets?.map(b => ({
          field: b.field,
          interval: b.interval.toLowerCase() as BucketInterval,
          alias: b.alias,
        })),
        filter: combinedFilter,
      };

      return deps.objectManager.aggregate(typeName, query, requestContext);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Search resolvers ───

function generateSearchResolver(
  obj: ObjectType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const typeName = obj.name;
  const fgaType = toSnakeCase(typeName);

  // searchFoos(query, fields, filter, first, after): SearchResult_Foo!
  resolvers['Query']![`search${typeName}s`] = async (
    _parent: unknown,
    args: {
      query: string;
      fields?: string[];
      filter?: Record<string, unknown>;
      first?: number;
      after?: string;
    },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Reject empty search queries
      if (!args.query || args.query.trim().length === 0) {
        throw createAltiusError({
          code: 'INVALID_ARGUMENT',
          category: 'validation',
          message: 'Search query must not be empty',
          retryable: false,
          traceId: requestContext.traceId,
        });
      }

      // Authorization: restrict search to authorized objects
      const allowedIds = await resolveAllowedIds(deps, user.id, fgaType, user.tenantId);
      if (allowedIds.length === 0) {
        return { hits: [], totalCount: 0, hasNextPage: false };
      }

      // Convert GraphQL filter to SPI filter and combine with auth filter
      const userFilter = convertFilter(args.filter);

      // SEC-14: Validate search/filter fields against redacted fields
      const visibleFields = deps.authorizationService.getVisibleFields(user.id, user.roles, typeName);
      const searchFieldViolations = validateQueryFields(
        extractFilterFields(userFilter),
        [],
        visibleFields,
      );
      // Also validate explicitly requested search fields
      if (args.fields && visibleFields) {
        for (const f of args.fields) {
          if (!visibleFields.has(f)) searchFieldViolations.push(f);
        }
      }
      if (searchFieldViolations.length > 0) {
        throw new Error(
          `Access denied: cannot search or filter on redacted fields: ${searchFieldViolations.join(', ')}`,
        );
      }

      // SEC-14b: When no explicit search fields provided and redaction is active,
      // restrict search to visible fields only (prevents hidden field leakage).
      let searchFields = args.fields;
      if (!searchFields && visibleFields) {
        searchFields = [...visibleFields].filter(f => !f.startsWith('_'));
      }

      const combinedFilter = buildAuthFilter(allowedIds, userFilter);

      // Resolve pagination: 'after' is an opaque cursor encoding an offset
      let offset = 0;
      if (args.after) {
        offset = decodeCursor(args.after) + 1;
      }

      const limit = args.first ?? 20;
      type Hit = { object: OntologyObject; score: number };
      type ShapedHit = { node: Record<string, unknown>; score: number };
      const searchWith = (l: number, o: number): SearchQuery => ({
        query: args.query, fields: searchFields, filter: combinedFilter, limit: l, offset: o,
      });
      const mapHits = (rawHits: Hit[]): ShapedHit[] => {
        const redacted = deps.authorizationService.redactFieldsBatch(
          user.id, user.roles, typeName,
          rawHits.map((h) => objectToGraphQL(h.object, obj)),
        );
        return redacted.map((r: RedactionResult<Record<string, unknown>>, i: number) => {
          const data = r.data as Record<string, unknown>;
          data._redactedFields = r._redactedFields.length > 0 ? r._redactedFields : null;
          data._consentRestricted = false;
          return { node: data, score: rawHits[i]!.score };
        });
      };

      let hits: ShapedHit[];
      let totalCount: number;
      let hasNextPage: boolean;

      if (deps.consentService && isConsentSubjectType(typeName, deps.consentSubjectTypes)) {
        const getPrimaryId = (hit: ShapedHit) => String(hit.node._id ?? '');
        const result = await paginateWithConsent<Hit, ShapedHit>(
          offset,
          limit,
          async (windowLimit) => {
            const r = await deps.objectManager.search(typeName, searchWith(windowLimit, 0), requestContext);
            return { items: r.hits as Hit[], total: r.totalCount };
          },
          async (rawHits) => {
            const consentResult = await deps.consentService!.filterList(
              mapHits(rawHits), getPrimaryId, DEFAULT_CONSENT_PURPOSE as DataPurpose,
              user.id, requestContext.tenantId,
            );
            return consentResult.edges as ShapedHit[];
          },
        );
        hits = result.items;
        totalCount = result.totalCount;
        hasNextPage = result.hasNextPage;
      } else {
        const r = await deps.objectManager.search(typeName, searchWith(limit, offset), requestContext);
        hits = mapHits(r.hits as Hit[]);
        totalCount = r.totalCount;
        hasNextPage = offset + hits.length < totalCount;
      }

      return { hits, totalCount, hasNextPage };
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Mutation resolvers ───

function generateMutationResolver(
  action: ActionType,
  schema: ParsedSchema,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const fieldName = lowerFirst(action.name);

  resolvers['Mutation']![fieldName] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      const { user, requestContext } = ctx;

      // Build ActionActor from authenticated user
      const actor: ActionActor = {
        id: user.id,
        type: 'user',
        roles: user.roles,
      };

      // Build ActionContext — derive consent from action schema. If the action
      // has a @param whose type is a configured consent-subject type (default
      // Patient), check consent for that subject under the default purpose.
      const subjectTypes = deps.consentSubjectTypes ?? DEFAULT_CONSENT_SUBJECT_TYPES;
      const subjectParam = action.fields.find(
        f => isParamField(f) && subjectTypes.includes(f.type.name),
      );
      const consentSubjectId = subjectParam
        ? String(args.input[subjectParam.name] ?? '')
        : undefined;
      // Optimistic concurrency: GraphQL hides transport, so the version the
      // caller decided on arrives as a reserved input field rather than an
      // If-Match header (the REST equivalent).
      const expectedVersion = args.input?.['_expectedVersion'];

      const actionCtx: ActionContext = {
        requestContext,
        ...(consentSubjectId ? {
          consentPurpose: DEFAULT_CONSENT_PURPOSE,
          consentSubjectId,
        } : {}),
        ...(typeof expectedVersion === 'number' ? { expectedVersion } : {}),
      };

      // Resolve manifest from registry — fail closed if not found
      const manifest = deps.manifestRegistry?.get(action.name);
      if (!manifest) {
        return {
          success: false,
          actionId: `err_${Date.now().toString(36)}`,
          errors: [{ code: 'MANIFEST_NOT_FOUND', message: `No manifest registered for action "${action.name}"` }],
          affectedObjects: [],
        };
      }

      // Execute via ActionExecutor
      const result = await deps.actionExecutor.execute(
        manifest,
        args.input,
        actor,
        actionCtx,
        schema,
        { dryRun: args.input?.['dryRun'] === true },
      );

      // Change events reach subscribers via the event bus path:
      // ActionExecutor → eventPublisher → emitter → eventBus → SubscriptionManager → PubSub.
      // No direct PubSub publish here to avoid duplicate delivery on the same pod.

      return {
        success: result.success,
        actionId: result.actionId,
        errors: result.errors.length > 0 ? result.errors : null,
        affectedObjects: result.affectedObjects.map(o => ({
          typeName: o.type,
          id: o.id,
          changeType: o.changeType.toUpperCase(),
        })),
      };
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Function resolvers (Section 6 — Functions) ───

/**
 * Generate a mutation resolver for a FunctionType.
 *
 * The resolver delegates to `deps.functionExecutor`. Functions are pure
 * computations: there is no ActionExecutor, no manifest, no consent
 * subject, and no affected-objects payload. The result shape matches the
 * `${name}FunctionResult` SDL type.
 *
 * Authorization: role-based and fail-closed — the caller must hold one of the
 * FunctionType's `requiredRoles`, and a function declaring none is denied
 * rather than allowed. A function runs pack-authored code, so leaving it
 * ungated would let the same logic ship as a function to bypass every control
 * the action pipeline applies. Roles rather than a ReBAC relation because the
 * inputs are scalars: there is no object for OpenFGA to resolve against.
 *
 * Success, denial, and a throw from inside the pack code are all audited
 * best-effort — a failed audit write is logged, never surfaced to the caller.
 */
function generateFunctionResolver(
  fn: FunctionType,
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  const fieldName = `${lowerFirst(fn.name)}Function`;

  resolvers['Mutation']![fieldName] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      // Authorization and audit live in invokeFunction, shared with the REST
      // route — they belong to the function, not to GraphQL.
      return await invokeFunction(fn, deps, ctx, args.input ?? {});
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

// ─── Subscription resolvers ───

function generateSubscriptionResolvers(
  obj: ObjectType,
  resolvers: ResolverMap,
  pubsub: PubSub,
): void {
  const lower = lowerFirst(obj.name);
  const topic = `${lower}Changed`;

  // fooChanged(id: ID!) — subscribe to changes on a specific object
  resolvers['Subscription']![topic] = createIdFilteredSubscription(pubsub, topic);

  // foosChanged(filter: FooFilter) — subscribe to all changes on a type
  resolvers['Subscription']![`${lower}sChanged`] = createFilteredSubscription(pubsub, topic);
}

// ─── availableTools resolver (Section 5.7) ───

/**
 * Discovery authorization (spec §5.7.1): every action is returned to any
 * authenticated caller — no per-user filtering. Action permissions are
 * object-scoped FGA relations (can_<verb> on the target object), so "can this
 * user use this tool" has no type-level answer, and introspection exposes the
 * same mutations anyway. Enforcement happens at execution time in the action
 * pipeline; requiredPermissions is advisory metadata.
 *
 * Descriptor generation is delegated to ToolRegistry (@altius/actions) — the
 * single builder shared with library/agent embeddings.
 */
function generateAvailableToolsResolver(
  schema: ParsedSchema,
  deps: ApiDependencies,
): (_parent: unknown, args: { filter?: { kind?: string; tags?: string[] } }, _ctx: ResolverContext) => unknown[] {
  const manifests = new Map<string, ActionManifest>();
  for (const action of schema.actionTypes) {
    const manifest = deps.manifestRegistry?.get(action.name);
    if (manifest) manifests.set(action.name, manifest);
  }
  const registry = new ToolRegistry({ schema, manifests });

  const tools = registry.availableTools().map((d) => ({
    ...d,
    // The HTTP surface now accepts a dryRun flag on both REST (?dryRun=true)
    // and GraphQL (dryRun: true in the mutation input), so the descriptor
    // accurately advertises it.
    dryRunSupported: true,
    // SDL requires tags; descriptors don't carry pack tags yet.
    tags: [] as string[],
  }));

  return (_parent, args) => {
    let filtered = tools;

    if (args.filter?.kind) {
      filtered = filtered.filter(t => t.kind === args.filter!.kind);
    }
    if (args.filter?.tags && args.filter.tags.length > 0) {
      const filterTags = new Set(args.filter.tags);
      filtered = filtered.filter(t => t.tags.some((tag: string) => filterTags.has(tag)));
    }

    return filtered;
  };
}

// ─── Per-object action applicability resolver ───

/**
 * Resolve which actions apply to a given object. An action "applies" to an
 * object when it has a @param field whose type is that ObjectType — the
 * action's target is that object. The caller must also have FGA viewer
 * access to the object; without that, the action list is empty so a
 * right-click menu never offers actions on a row the user cannot see.
 *
 * This is a read-only check — no manifest is loaded, no preconditions are
 * evaluated, no effects are applied. It answers "which actions COULD this
 * row trigger?", not "would they succeed?".
 */
function generateApplicableActionsResolver(
  schema: ParsedSchema,
  deps: ApiDependencies,
): (_parent: unknown, args: { objectType: string; objectId: string }, ctx: ResolverContext) => Promise<string[]> {
  // Pre-compute: for each ObjectType, which actions target it?
  const actionsByTargetType = new Map<string, string[]>();
  for (const action of schema.actionTypes) {
    for (const field of action.fields) {
      const isParam = field.directives.some((d) => d.kind === 'param');
      if (!isParam) continue;
      if (schema.objectTypes.some((ot) => ot.name === field.type.name)) {
        const list = actionsByTargetType.get(field.type.name) ?? [];
        list.push(action.name);
        actionsByTargetType.set(field.type.name, list);
        break; // one targeting param is enough
      }
    }
  }

  return async (_parent, args, ctx) => {
    const { user } = ctx;
    const candidates = actionsByTargetType.get(args.objectType) ?? [];
    if (candidates.length === 0) return [];

    // FGA viewer check on the object — fail-closed
    const fgaType = toSnakeCase(args.objectType);
    const allowed = await deps.authorizationService.check(
      `user:${user.id}`,
      'viewer',
      `${fgaType}:${args.objectId}`,
      user.tenantId,
    );
    if (!allowed) return [];

    return candidates;
  };
}

// ─── Object Set resolvers ───

function generateObjectSetResolvers(
  resolvers: ResolverMap,
  deps: ApiDependencies,
): void {
  // Query: objectSet(id: ID!): ObjectSet
  resolvers['Query']!['objectSet'] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) return null;
      const def = await deps.objectSetManager.get(args.id, ctx.requestContext);
      return def ? objectSetToGraphQL(def) : null;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Query: objectSets(objectType: String): [ObjectSet!]!
  resolvers['Query']!['objectSets'] = async (
    _parent: unknown,
    args: { objectType?: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) return [];
      const defs = await deps.objectSetManager.list(args.objectType, ctx.requestContext);
      return defs.map(objectSetToGraphQL);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: createObjectSet(input: CreateObjectSetInput!): ObjectSet!
  resolvers['Mutation']!['createObjectSet'] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createAltiusError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      const def = await deps.objectSetManager.create(
        {
          name: args.input['name'] as string,
          description: args.input['description'] as string | undefined,
          objectType: args.input['objectType'] as string,
          filter: args.input['filter'] as FilterExpression | undefined,
          orderBy: args.input['orderBy'] as { field: string; direction: 'asc' | 'desc' }[] | undefined,
          limit: args.input['limit'] as number | undefined,
          aggregation: args.input['aggregation'] as AggregateQuery | undefined,
          isPublic: (args.input['isPublic'] as boolean) ?? false,
          createdBy: ctx.user.id,
          tenantId: ctx.requestContext.tenantId,
        },
        ctx.requestContext,
      );
      return objectSetToGraphQL(def);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: updateObjectSet(id: ID!, input: UpdateObjectSetInput!): ObjectSet!
  resolvers['Mutation']!['updateObjectSet'] = async (
    _parent: unknown,
    args: { id: string; input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createAltiusError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      const ALLOWED_UPDATE_FIELDS = new Set(['name', 'description', 'filter', 'orderBy', 'limit', 'aggregation', 'isPublic']);
      const updates: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(args.input)) {
        if (value !== undefined && ALLOWED_UPDATE_FIELDS.has(key)) {
          updates[key] = value;
        }
      }
      const def = await deps.objectSetManager.update(args.id, updates, ctx.requestContext);
      return objectSetToGraphQL(def);
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };

  // Mutation: deleteObjectSet(id: ID!): Boolean!
  resolvers['Mutation']!['deleteObjectSet'] = async (
    _parent: unknown,
    args: { id: string },
    ctx: ResolverContext,
  ) => {
    try {
      if (!deps.objectSetManager) {
        throw createAltiusError({
          code: 'NOT_CONFIGURED',
          category: 'system',
          message: 'Object set manager is not configured',
          retryable: false,
          traceId: ctx.requestContext.traceId,
        });
      }
      await deps.objectSetManager.delete(args.id, ctx.requestContext);
      return true;
    } catch (err) {
      throw wrapError(err, ctx.requestContext.traceId);
    }
  };
}

/**
 * Map the CDM read-only projection onto GraphQL queries, reusing the exact same
 * handlers as the REST /api/v1/cdm/* router (auth + redaction + consent +
 * profile-driven projection). Records are returned via the JSON scalar because
 * the CDM shape is profile-driven and intentionally flexible.
 */
function generateCdmResolvers(resolvers: ResolverMap, deps: ApiDependencies): void {
  // Translate a non-200 CdmResponse into a GraphQL error.
  const throwForStatus = (status: number, body: unknown, traceId: string | undefined): never => {
    const message =
      (body as { error?: { message?: string } })?.error?.message ?? 'CDM request failed';
    const category: ErrorCategory =
      status === 401 || status === 403 ? 'authorization'
      : status === 404 ? 'not_found'
      : status === 400 ? 'validation'
      : 'system';
    throw createAltiusError({
      code: `CDM_${status}`,
      category,
      message,
      retryable: false,
      traceId,
    });
  };

  // Query: cdmMetadata: JSON! — public profile + compatibility matrix + gaps.
  resolvers['Query']!['cdmMetadata'] = async () => buildCdmMetadata();

  // Query: cdmRecord(sourceType, id): JSON
  resolvers['Query']!['cdmRecord'] = async (
    _parent: unknown,
    args: { sourceType: string; id: string },
    ctx: ResolverContext,
  ) => {
    if (!OBJECT_SOURCE_TYPES.includes(args.sourceType)) {
      throwForStatus(404, { error: { message: `CDM source type '${args.sourceType}' is not exposed.` } }, ctx.requestContext.traceId);
    }
    const res = await handleObjectRead(deps, ctx.user, args.sourceType, args.id);
    if (res.status !== 200) throwForStatus(res.status, res.body, ctx.requestContext.traceId);
    return res.body;
  };

  // Query: cdmRecords(sourceType): JSON! — { resourceType, total, truncated, records }
  resolvers['Query']!['cdmRecords'] = async (
    _parent: unknown,
    args: { sourceType: string },
    ctx: ResolverContext,
  ) => {
    if (!OBJECT_SOURCE_TYPES.includes(args.sourceType)) {
      throwForStatus(404, { error: { message: `CDM source type '${args.sourceType}' is not exposed.` } }, ctx.requestContext.traceId);
    }
    const res = await handleObjectList(deps, ctx.user, args.sourceType);
    if (res.status !== 200) throwForStatus(res.status, res.body, ctx.requestContext.traceId);
    return res.body;
  };

  // Query: cdmEncounters(patient): JSON! — link-kind Encounter projection
  // (derived from AdmittedTo), mirroring REST /api/v1/cdm/Encounter?patient=.
  resolvers['Query']!['cdmEncounters'] = async (
    _parent: unknown,
    args: { patient: string },
    ctx: ResolverContext,
  ) => {
    const res = await handleEncounterSearch(
      deps,
      { method: 'GET', path: 'Encounter', query: { patient: args.patient }, user: ctx.user },
      ctx.user,
    );
    if (res.status !== 200) throwForStatus(res.status, res.body, ctx.requestContext.traceId);
    return res.body;
  };
}

/**
 * Care-team relationship grant/revoke mutations (v0.2.0 A1), reusing the exact
 * same core (validation + allowlist + granter-role gate + audit) as the REST
 * /api/v1/relationships routes. Maps the structured result onto GraphQL errors.
 */
function generateRelationshipResolvers(resolvers: ResolverMap, deps: ApiDependencies): void {
  const run = (action: 'grant' | 'revoke') => async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    const { user, requestContext } = ctx;
    const result = await applyRelationshipChange(
      deps,
      deps.grantAllowlist ?? new Map(),
      action,
      args.input,
      { id: user.id, roles: user.roles, tenantId: requestContext.tenantId },
      requestContext.traceId,
    );
    if (!result.ok) {
      throw createAltiusError({
        code: result.code ?? 'RELATIONSHIP_ERROR',
        category: (result.category ?? 'system') as ErrorCategory,
        message: result.message ?? 'Relationship change failed',
        retryable: result.category === 'system',
        traceId: requestContext.traceId,
      });
    }
    const d = result.data!;
    return { subject: d['subject'], relation: d['relation'], object: d['object'], ok: true };
  };

  resolvers['Mutation']!['grantRelationship'] = run('grant');
  resolvers['Mutation']!['revokeRelationship'] = run('revoke');
}

/**
 * Consent-record mutation (v0.2.0 A2), reusing the same core (validation +
 * recorder-role gate + audit) as the REST /api/v1/consent route.
 */
function generateConsentResolvers(resolvers: ResolverMap, deps: ApiDependencies): void {
  resolvers['Mutation']!['recordConsent'] = async (
    _parent: unknown,
    args: { input: Record<string, unknown> },
    ctx: ResolverContext,
  ) => {
    const { user, requestContext } = ctx;
    const result = await applyConsentRecord(
      deps, args.input,
      { id: user.id, roles: user.roles }, requestContext.tenantId, requestContext.traceId,
    );
    if (!result.ok) {
      throw createAltiusError({
        code: result.code ?? 'CONSENT_ERROR',
        category: (result.category ?? 'system') as ErrorCategory,
        message: result.message ?? 'Consent record failed',
        retryable: result.category === 'system',
        traceId: requestContext.traceId,
      });
    }
    return result.data;
  };
}

function objectSetToGraphQL(def: {
  id: string;
  name: string;
  description?: string;
  objectType: string;
  filter?: unknown;
  orderBy?: unknown;
  limit?: number;
  aggregation?: unknown;
  isPublic: boolean;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}): Record<string, unknown> {
  return {
    id: def.id,
    name: def.name,
    description: def.description ?? null,
    objectType: def.objectType,
    filter: def.filter ?? null,
    orderBy: def.orderBy ?? null,
    limit: def.limit ?? null,
    aggregation: def.aggregation ?? null,
    isPublic: def.isPublic,
    createdBy: def.createdBy,
    createdAt: def.createdAt,
    updatedAt: def.updatedAt,
  };
}
