{{- if gt (int .Values.actionExecutor.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "altius.fullname" . }}-action-executor
  labels:
    {{- include "altius.labels" . | nindent 4 }}
    app.kubernetes.io/component: action-executor
spec:
  minAvailable: {{ .Values.actionExecutor.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "altius.selectorLabels" (dict "name" "action-executor" "release" .Release.Name) | nindent 6 }}
{{- end }}
