/**
 * AI FDE agentic platform assistant.
 *
 * A mode-scoped agent that performs platform work: data integration,
 * ontology editing, functions, governance audit, ML, OSDK React.
 * Capabilities include plan generation, clarification, and executing actions.
 */

import type { RequestContext } from './ontology.js';

// ===========================================================================
// Agent modes
// ===========================================================================

/** The operational mode of the platform assistant. */
export type AgentMode =
  | 'data_integration'   // configure connectors, mappings, pipelines
  | 'ontology_editing'    // create/modify object types, links, properties
  | 'functions'            // author and deploy functions
  | 'governance_audit'    // audit permissions, consent, markings
  | 'ml'                  // manage model registry, training, inference
  | 'osdk_react'          // generate SDK code and React components
  | 'general';            // general-purpose assistant

// ===========================================================================
// Plans
// ===========================================================================

/** A step in an agent plan. */
export interface PlanStep {
  /** Step ID. */
  id: string;
  /** Step description. */
  description: string;
  /** The action/tool to invoke. */
  action: string;
  /** Parameters for the action. */
  params: Record<string, unknown>;
  /** Dependencies (step IDs that must complete first). */
  dependsOn: string[];
  /** Expected outcome. */
  expectedOutcome: string;
  /** Whether the step is reversible. */
  reversible: boolean;
  /** Risk level. */
  riskLevel: 'low' | 'medium' | 'high';
}

/** A plan generated by the assistant. */
export interface AgentPlan {
  id: string;
  tenantId: string;
  /** The user's request. */
  request: string;
  /** The mode the plan was generated for. */
  mode: AgentMode;
  /** Ordered steps. */
  steps: PlanStep[];
  /** Whether the plan has been approved. */
  approved: boolean;
  /** Whether the plan is currently executing. */
  executing: boolean;
  /** Whether the plan completed. */
  completed: boolean;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** Who requested the plan. */
  requestedBy: string;
  /** Clarification questions (if the plan needs more info). */
  clarifications: ClarificationQuestion[];
  /** Whether the plan needs clarification before proceeding. */
  needsClarification: boolean;
}

/** A clarification question. */
export interface ClarificationQuestion {
  id: string;
  question: string;
  /** Suggested answers. */
  suggestions?: string[];
  /** Whether the question is required. */
  required: boolean;
  /** The user's answer (if provided). */
  answer?: string;
}

// ===========================================================================
// Plan execution
// ===========================================================================

/** Result of executing a plan step. */
export interface PlanStepResult {
  stepId: string;
  /** Whether the step succeeded. */
  success: boolean;
  /** Output of the step. */
  output: unknown;
  /** Error message (if failed). */
  error?: string;
  /** ISO 8601 execution timestamp. */
  executedAt: string;
  /** Duration in ms. */
  durationMs: number;
}

/** Result of executing a full plan. */
export interface PlanExecutionResult {
  planId: string;
  /** Whether all steps succeeded. */
  success: boolean;
  /** Per-step results. */
  stepResults: PlanStepResult[];
  /** ISO 8601 completion timestamp. */
  completedAt: string;
  /** Total duration in ms. */
  totalDurationMs: number;
}

// ===========================================================================
// Agent sessions
// ===========================================================================

/** An agent session — a conversation with the platform assistant. */
export interface AgentSession {
  id: string;
  tenantId: string;
  /** The mode for this session. */
  mode: AgentMode;
  /** Conversation messages. */
  messages: AgentMessage[];
  /** The active plan (if any). */
  activePlanId?: string;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** ISO 8601 last activity timestamp. */
  lastActivityAt: string;
  /** User ID who owns the session. */
  userId: string;
}

/** A message in an agent conversation. */
export interface AgentMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
  /** Tool calls made in this message (if assistant). */
  toolCalls?: Array<{ tool: string; params: Record<string, unknown>; result?: unknown }>;
  /** Whether the message is a clarification. */
  isClarification?: boolean;
}

// ===========================================================================
// Tool registry
// ===========================================================================

/** A tool the agent can invoke. */
export interface AgentTool {
  /** Tool name. */
  name: string;
  /** Description of what the tool does. */
  description: string;
  /** Mode(s) this tool is available in. */
  modes: AgentMode[];
  /** JSON-Schema for the tool's parameters. */
  paramSchema: Record<string, unknown>;
  /** Risk level of the tool. */
  riskLevel: 'low' | 'medium' | 'high';
  /** Whether the tool requires approval before execution. */
  requiresApproval: boolean;
  /** Execute the tool. */
  execute: (params: Record<string, unknown>, ctx: RequestContext) => Promise<unknown>;
}

// ===========================================================================
// Platform assistant service
// ===========================================================================

/** Input for starting a session. */
export interface StartSessionInput {
  mode: AgentMode;
  initialRequest?: string;
}

/** Input for sending a message. */
export interface SendMessageInput {
  sessionId: string;
  message: string;
  /** Answers to clarification questions (if responding to clarifications). */
  clarificationAnswers?: Record<string, string>;
}

/**
 * AI FDE agentic platform assistant — mode-scoped agent that performs
 * platform work with plan generation, clarification, and action execution.
 */
export interface PlatformAssistantService {
  // ── Sessions ──
  startSession(ctx: RequestContext, input: StartSessionInput): Promise<AgentSession>;
  getSession(ctx: RequestContext, sessionId: string): Promise<AgentSession | null>;
  listSessions(ctx: RequestContext, userId?: string): Promise<AgentSession[]>;
  deleteSession(ctx: RequestContext, sessionId: string): Promise<void>;

  // ── Conversation ──
  sendMessage(ctx: RequestContext, input: SendMessageInput): Promise<AgentMessage>;

  // ── Planning ──
  /** Generate a plan for a request in the given mode. */
  generatePlan(ctx: RequestContext, mode: AgentMode, request: string): Promise<AgentPlan>;
  /** Get a plan by ID. */
  getPlan(ctx: RequestContext, planId: string): Promise<AgentPlan | null>;
  /** List plans for a tenant. */
  listPlans(ctx: RequestContext, mode?: AgentMode): Promise<AgentPlan[]>;
  /** Approve a plan. */
  approvePlan(ctx: RequestContext, planId: string): Promise<AgentPlan>;
  /** Reject a plan. */
  rejectPlan(ctx: RequestContext, planId: string): Promise<void>;
  /** Answer clarification questions. */
  answerClarifications(ctx: RequestContext, planId: string, answers: Record<string, string>): Promise<AgentPlan>;

  // ── Execution ──
  /** Execute an approved plan. */
  executePlan(ctx: RequestContext, planId: string): Promise<PlanExecutionResult>;
  /** Get execution result for a plan. */
  getExecutionResult(ctx: RequestContext, planId: string): Promise<PlanExecutionResult | null>;

  // ── Tools ──
  /** Register a tool. */
  registerTool(ctx: RequestContext, tool: AgentTool): Promise<void>;
  /** List available tools for a mode. */
  listTools(ctx: RequestContext, mode: AgentMode): Promise<Array<Omit<AgentTool, 'execute'>>>;
}
